trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '1'
    scanWebSites: '32bd8bc5-5aa7-430d-3365-afd90226256d'
    buildFail: true
    severity: 'Critical,High'