trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '1'
    scanWebSites: 'b45e158b-7190-4934-6d65-aefd033fcdb6'
    hasReport: true
    reportType: 'ScanDetail'