trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '1'
    scanWebSites: '41605a36-ddb3-471a-3585-b1bd03393a2a'
    hasReport: true
    reportType: 'ScanDetail'