trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: 'a8d288cf-7da1-4802-18de-ae6d01e657dd'
    scanWebSitesProfile: '115f7677-c560-46e0-5be1-af41020e5bd7'
    buildFail: true
    severity: 'Critical,High,Medium'