trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: '2e1498ff-ad9a-4569-c4e4-ae8301b8e800'
    scanWebSitesProfile: '66094dd8-ee80-43d8-d8fc-af2e03a15091'
    buildFail: true
    severity: 'Critical,High,Medium'
    hasReport: true