trigger:
  - master

pool:
  vmImage: 'windows-latest'


steps:

- checkout: CICD containers
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls ''$(Build.SourcesDirectory)'''
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Get-Content -Path $(Build.SourcesDirectory)\test.json'