trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '0'
    scanWebSites: 'b45e158b-7190-4934-6d65-aefd033fcdb6'
    scanWebSitesProfile: 'a2985058-7f9e-4c8d-eb00-af1901f9f767'
    hasReport: true
    reportType: 'ScanDetail'
    excludeAddressedIssues: false