trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: acunetix360@1
  inputs:
    apiConnection: 'ACX 360 trigger'
    scanTypes: '1'
    scanWebSites: 'c925f212-2ee0-43dd-fef9-af0002ee8ab0'
    buildFail: true
    severity: 'Critical'
    isConfirmed: true