trigger:
  - master

pool:
  vmImage: 'windows-latest'


steps:
- task: netsparker-cloud@1
  inputs:
    apiConnection: 'azuredevopstest'
    scanTypes: '2'
    scanWebSites: '2e1498ff-ad9a-4569-c4e4-ae8301b8e800'
    scanWebSitesProfile: '3603c9cd-31b1-40a6-be06-af3f02a66845'
    buildFail: true
    severity: 'Critical'
    hasReport: true
    reportType: 'OwaspTopTen2017'
    isConfirmed: true

